# Лабораторна №1
## Вагін Олександр КА-01

Імпортуємо бібліотеку NumPy

In [1]:
import numpy as np

Створюємо масив використовуючі випадкові значення від 0 до 10

In [2]:
N = 100
m = 4
T = np.random.randint(10, size=(N, m))
T

array([[9, 6, 4, 9],
       [5, 5, 5, 2],
       [4, 6, 2, 2],
       [8, 6, 4, 3],
       [8, 8, 3, 1],
       [8, 8, 0, 4],
       [5, 3, 2, 5],
       [4, 0, 3, 1],
       [8, 7, 0, 7],
       [5, 7, 0, 7],
       [8, 3, 9, 6],
       [5, 6, 8, 4],
       [8, 9, 8, 7],
       [6, 1, 2, 2],
       [2, 7, 8, 1],
       [1, 8, 8, 1],
       [9, 3, 5, 1],
       [8, 0, 8, 9],
       [4, 3, 5, 7],
       [6, 0, 9, 9],
       [3, 4, 6, 5],
       [2, 8, 3, 5],
       [8, 9, 5, 0],
       [8, 9, 8, 4],
       [4, 1, 9, 0],
       [7, 9, 7, 2],
       [7, 7, 1, 9],
       [3, 7, 9, 3],
       [3, 6, 4, 0],
       [1, 9, 5, 2],
       [6, 9, 6, 1],
       [7, 5, 9, 2],
       [8, 5, 8, 0],
       [9, 2, 8, 1],
       [1, 0, 4, 0],
       [1, 4, 5, 6],
       [3, 3, 6, 7],
       [2, 9, 1, 8],
       [1, 3, 9, 4],
       [0, 8, 5, 8],
       [3, 7, 8, 4],
       [8, 3, 8, 6],
       [9, 0, 4, 5],
       [5, 8, 4, 2],
       [7, 3, 0, 8],
       [6, 4, 3, 1],
       [3, 1, 2, 4],
       [9, 4,

Створюємо вектор міток классів

In [3]:
number_of_clases = 3
y = np.random.randint(number_of_clases, size=(N))
y

array([1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1,
       0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 1, 1,
       2, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 0, 0, 0, 2, 2, 0, 0, 1,
       1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 0, 2, 0,
       1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0])

p1(x_h = c_hi) - кiлькiсть прикладiв, для яких ознака xh приймає значення ch_i

In [4]:
p1 = np.zeros(shape=(m, 10), dtype=np.int16)
for i in range(m):
    for j in range(10):
        p1[i, j] = np.count_nonzero(T[:,i] == j)
p1

array([[ 7,  8, 11, 13,  8,  8,  7, 10, 15, 13],
       [13,  9,  7, 11,  8,  8, 10, 12, 13,  9],
       [ 7,  7,  8, 12, 10, 11,  9,  5, 19, 12],
       [10, 15,  9,  8,  9,  9, 11, 12,  7, 10]], dtype=int16)

In [5]:
p2 = np.zeros(shape=(number_of_clases, m, 10), dtype=np.int16)
for i in range(N):
    for j in range(m):
        p2[y[i],j,T[i,:][j]]+=1
p2

array([[[2, 1, 2, 4, 4, 0, 3, 4, 2, 6],
        [4, 4, 2, 1, 2, 5, 3, 4, 1, 2],
        [1, 3, 3, 3, 2, 3, 1, 1, 5, 6],
        [5, 3, 2, 3, 2, 1, 3, 4, 2, 3]],

       [[3, 1, 5, 4, 1, 5, 0, 3, 8, 3],
        [4, 3, 3, 3, 1, 0, 4, 6, 9, 0],
        [4, 1, 2, 6, 5, 3, 1, 2, 7, 2],
        [2, 5, 3, 2, 4, 5, 3, 3, 1, 5]],

       [[2, 6, 4, 5, 3, 3, 4, 3, 5, 4],
        [5, 2, 2, 7, 5, 3, 3, 2, 3, 7],
        [2, 3, 3, 3, 3, 5, 7, 2, 7, 4],
        [3, 7, 4, 3, 3, 3, 5, 5, 4, 2]]], dtype=int16)

In [6]:
s = np.argmax(p2, axis=0)
s

array([[1, 2, 1, 2, 0, 1, 2, 0, 1, 0],
       [2, 0, 1, 2, 2, 0, 1, 1, 1, 2],
       [1, 0, 0, 1, 1, 2, 2, 1, 1, 0],
       [0, 2, 2, 0, 1, 1, 2, 2, 2, 1]])

In [7]:
p3 = np.zeros(shape=(m, 10), dtype=np.int16)
for i in range(N):
    for j in range(m):
        if y[i] != s[j, T[i,j]]:
            p3[j, T[i,j]]+=1
p3

array([[ 4,  2,  6,  8,  4,  3,  3,  6,  7,  7],
       [ 8,  5,  4,  4,  3,  3,  6,  6,  4,  2],
       [ 3,  4,  5,  6,  5,  6,  2,  3, 12,  6],
       [ 5,  8,  5,  5,  5,  4,  6,  7,  3,  5]], dtype=int16)

In [8]:
er = p3/p1
er

array([[0.57142857, 0.25      , 0.54545455, 0.61538462, 0.5       ,
        0.375     , 0.42857143, 0.6       , 0.46666667, 0.53846154],
       [0.61538462, 0.55555556, 0.57142857, 0.36363636, 0.375     ,
        0.375     , 0.6       , 0.5       , 0.30769231, 0.22222222],
       [0.42857143, 0.57142857, 0.625     , 0.5       , 0.5       ,
        0.54545455, 0.22222222, 0.6       , 0.63157895, 0.5       ],
       [0.5       , 0.53333333, 0.55555556, 0.625     , 0.55555556,
        0.44444444, 0.54545455, 0.58333333, 0.42857143, 0.5       ]])

In [13]:
np.argmin(er)//10, np.argmin(er) % 10

(1, 9)